// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableDrawerMode() {
  return window['go']['desktop']['App']['EnableDrawerMode']();
}

export function EnableFullUI() {
  return window['go']['desktop']['App']['EnableFullUI']();
}

export function GetStartupState() {
  return window['go']['desktop']['App']['GetStartupState']();
}

export function ToggleStartup(arg1) {
  return window['go']['desktop']['App']['ToggleStartup'](arg1);
}
