// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableDrawerMode():Promise<void>;

export function EnableFullUI():Promise<void>;

export function GetStartupState():Promise<boolean>;

export function ToggleStartup(arg1:boolean):Promise<void>;
